version: '3.8'

services:
  oviya-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ORCHESTRATOR_URL=http://oviya-backend:8000
    depends_on:
      - oviya-backend
    networks:
      - oviya-network

  oviya-backend:
    # This references your existing oviya-production backend
    # You can either:
    # 1. Build from your oviya-production directory
    # 2. Use an existing image
    # 3. Mount the directory
    build:
      context: ../oviya-production
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../oviya-production:/app
    networks:
      - oviya-network

networks:
  oviya-network:
    driver: bridge
